### ISSUE TITLE
Data transfer?

### ISSUE THREAD

**Issue by wuming123** [MinusKube/SmartInvs#1]
Hello there,
Can SmartInventory add custom content?
For example: InventoryContents.setProperty (k, v);

`public static final SmartInventory inv_task = SmartInventory.builder()`
			`  .id("Task_task")`
			`  .title("§9task")`
			`  .size(4, 9)`
			`  .provider(new Inv_Task())`
			`  .build();`
`class Inv_Task implements InventoryProvider {`
  `public void init(Player p, InvetoryContents inv) {`
    `System.out.print(inv.get(k));`
  `}`

`public void onChat(AsyncPlayerChatEvent evt) {`
    `inv_task.setProperty(k,v);`
`}`

**Comment by MinusKube** [comment]
You can get and set properties from the InventoryContents, and you can get a player's current InventoryContents using `InventoryManager#getContents(player)`.

For example:
```java
InventoryManager manager = SmartInvsPlugin.manager();
Optional<InventoryContents> opContents = manager.getContents(player);

if(opContents.isPresent()) {
    InventoryContents contents = opContents.get();
    contents.setProperty(key, value);
}
```

Then get a property using `contents.property(key)` or `contents.property(key, defaultValue)`.
