### ISSUE TITLE
InventoryContents#set

### ISSUE THREAD

**Issue by Rndstad** [MinusKube/SmartInvs#101]
Hey buddy, is there an option to add items with normal item slots? Like 22, 32?
So contents.set(22, ClickableItem)

**Comment by portlek** [comment]
There is actually;
https://github.com/portlek/vote/blob/master/src/main/java/io/github/portlek/vote/util/FileElement.java#L42

**Comment by Sytm** [comment]
Yeah, there is an option to set items using classic item-slots, it is just located at the 1.3.0 branch, which is not publicly available through Maven.

[Here is the method](https://github.com/MinusKube/SmartInvs/blob/ee1be735fb3e677dafe93fcca21ce6b9c4be6d45/src/main/java/fr/minuskube/inv/content/InventoryContents.java#L168)

**Comment by Rndstad** [comment]
Hello 👋🏻,

Thank you very much. Further, I have one important question: How can I drop items in the inventory, I tried everything without success. 

Regards,
Wael

**Comment by Rndstad** [comment]
I wanted to check adding listeners but your docs are down.

**Comment by MinusKube** [comment]
Hello, you can use `InventoryContents#setEditable(SlotPos, boolean)` in the 1.3.0 version (which is not released, we're still working on it).

And for the listeners, here's how they work:
```java
SmartInventory.builder()
        ...
        .listener(new InventoryListener(
            InventoryCloseEvent.class,
            event -> {
                Player player = (Player) event.getPlayer();
                player.sendMessage("You closed the inventory! Well played!");
            }
        )
        .build();
```

**Comment by Rndstad** [comment]
So the first I can’t use. When will it be released? So with the listeners I can still achieve the same result?

**Comment by Rndstad** [comment]
> Hello, you can use `InventoryContents#setEditable(SlotPos, boolean)` in the 1.3.0 version (which is not released, we're still working on it).
> 
> And for the listeners, here's how they work:
> 
> ```java
> SmartInventory.builder()
>         ...
>         .listener(new InventoryListener(
>             InventoryCloseEvent.class,
>             event -> {
>                 Player player = (Player) event.getPlayer();
>                 player.sendMessage("You closed the inventory! Well played!");
>             }
>         )
>         .build();
> ```

Unfortunately, event#getPlayer doesn't work. I copied your listeners solution quote.

**Comment by Rndstad** [comment]
Never mind, I fixed the problem. ;) 
So, with this method I can select a few places in the inventory that are draggable with items?

**Comment by MinusKube** [comment]
Yes, but I haven't fully tested it yet.

**Comment by Rndstad** [comment]
Ah alright. This is my code but it doesn't really work it, maybe you can take a look? 
` public static SmartInventory getInventory(FDCore fdCore, FinePlayer fp) {
        return SmartInventory.builder()
                .listener(new InventoryListener<>(
                        InventoryDragEvent.class,
                        e -> {
                            Player p = (Player) e.getWhoClicked();
                            System.out.println("1");
                            if (e.getView().getTitle().equals(getInventory(fdCore, fdCore.getPlayerManager().getFinePlayer(p.getUniqueId())).getTitle())) {
                                System.out.println("2");
                                // TODO CHECKING ITEM IF IT"S UPGRADABLE ITEM & IF SLOT WHERE ITEM IS PUT IS EMPTY + LIMITED SLOTS
                                if (e.getOldCursor().getType() != null) {
                                    System.out.println(e.getOldCursor());
                                    System.out.println(e.getNewItems());

                                    int position = 0;
                                    for (Map.Entry<Integer, ItemStack> entry : e.getNewItems().entrySet()) {
                                        if (ItemStackUtils.compareItems(entry.getValue(), e.getOldCursor())) {
                                            position = entry.getKey();
                                        }
                                    }
                                    fdCore.getPlayerManager().getFinePlayer(p.getUniqueId()).getUpgradeItems().put(position, e.getOldCursor());
                                    System.out.println("MAP & POSITION" + fdCore.getPlayerManager().getFinePlayer(p.getUniqueId()).getUpgradeItems() + " POSITION: " + position);
                                    e.setCancelled(false);
                                }
                            }
                            e.setCancelled(true);
                        }
                ))
                .listener(new InventoryListener<>(InventoryClickEvent.class, e -> {
                    Player p = (Player) e.getWhoClicked();
                    if (e.getView().getTitle().equals(getInventory(fdCore, fdCore.getPlayerManager().getFinePlayer(p.getUniqueId())).getTitle())) {
                        if (e.getClickedInventory().getType() == InventoryType.CHEST) {
                            if (e.getCursor() != null && e.getCursor().getType() != Material.AIR) {
                                // TODO CHECKING ITEM IF IT"S UPGRADABLE ITEM & IF SLOT WHERE ITEM IS PUT IS EMPTY + LIMITED SLOTS
                                System.out.println("ICE: " + e.getCurrentItem()); // dit is slot
                                System.out.println("ICE: " + e.getCursor()); // dit is cursor
//                    e.setCurrentItem(e.getCursor());
                            }
                        }
                    }
                }))
                .provider(new PersonalUpgradeInventory(fdCore, fp))
                .manager(fdCore.getInventoryManager())
                .size(6, 9)
                .title("Ability menu of " + Bukkit.getPlayer(fp.getUniqueId()).getName())
                .build();
    }`

**Comment by Rndstad** [comment]
You know, sometimes it works, most of the times it doesn't, look this is a video I made: https://streamable.com/q8i50

**Comment by Rndstad** [comment]
Any idea?

**Comment by MinusKube** [comment]
That looks like it's working for the InventoryDragEvent but not the InventoryClickEvent, I'll investigate on this ASAP.

**Comment by Rndstad** [comment]
> That looks like it's working for the InventoryDragEvent but not the InventoryClickEvent, I'll investigate on this ASAP.

Thank you very much! :)

**Comment by Rndstad** [comment]
> That looks like it's working for the InventoryDragEvent but not the InventoryClickEvent, I'll investigate on this ASAP.

What do you recommend me meanwhile, because I have a deadline on this project.

**Comment by Sytm** [comment]
> > That looks like it's working for the InventoryDragEvent but not the InventoryClickEvent, I'll investigate on this ASAP.
> 
> What do you recommend me meanwhile, because I have a deadline on this project.

One option would be to fork the repo and fix it yourself and the pr into this repo or just clone it and do it the hacky way on your machine only

**Comment by Rndstad** [comment]
> > > That looks like it's working for the InventoryDragEvent but not the InventoryClickEvent, I'll investigate on this ASAP.
> > 
> > 
> > What do you recommend me meanwhile, because I have a deadline on this project.
> 
> One option would be to fork the repo and fix it yourself and the pr into this repo or just clone it and do it the hacky way on your machine only

I still need to use it on Maven.

**Comment by Sytm** [comment]
Make changes and then run `./gradlew install`. Should install it into your local maven repository and should be used by your project over the other variant.

How did you even get the 1.3.0 in maven though?

**Comment by Rndstad** [comment]
> Make changes and then run `./gradlew install`. Should install it into your local maven repository and should be used by your project over the other variant.
> 
> How did you even get the 1.3.0 in maven though?

I didn't, that's the problem because in 1.3.0, it is fixed right?

**Comment by Sytm** [comment]
> I didn't

What? The feature is only available in the 1.3.0 branch, how did you even get that?

**Comment by Rndstad** [comment]
> > I didn't
> 
> What? The feature is only available in the 1.3.0 branch, how did you even get that?

Which feature?

**Comment by Sytm** [comment]
setEditable(), the one you are having problems with

**Comment by Rndstad** [comment]
> setEditable(), the one you are having problems with

No of course not, that would be the solution. But that is in 1.3.0, I don't have that version.

**Comment by Sytm** [comment]
And how did you get that feature shown in the streamable link to work where you can drag stuff into it?

**Comment by Rndstad** [comment]
> And how did you get that feature shown in the streamable link to work where you can drag stuff into it?

If you read my code, I tried to make it, but it doesn't work because the drag events of SmartInvs bug. You can do the exact same as me, but it will bug heavily.

**Comment by Sytm** [comment]
I don't know how well the setEditable function works, but I do have a private repo where I have the 1.3.0 branch hosted which I use for my plugins. I don't know if @MinusKube is ok with that, that I share  this:
```xml
<repository>
  <id>sytm-nexus</id>
  <url>https://repo.sytm.de/repository/maven-hosted/</url>
</repository>
---
<dependency>
  <groupId>fr.minuskube.inv</groupId>
  <artifactId>smart-invs</artifactId>
  <version>1.3.0-SNAPSHOT</version>
</dependency>
```
gn

**Comment by Rndstad** [comment]
> I don't know how well the setEditable function works, but I do have a private repo where I have the 1.3.0 branch hosted which I use for my plugins. I don't know if @MinusKube is ok with that, that I share this:
> 
> ```
> <repository>
>   <id>sytm-nexus</id>
>   <url>https://repo.sytm.de/repository/maven-hosted/</url>
> </repository>
> ---
> <dependency>
>   <groupId>fr.minuskube.inv</groupId>
>   <artifactId>smart-invs</artifactId>
>   <version>1.3.0-SNAPSHOT</version>
> </dependency>
> ```
> 
> gn

Anyway, I'm alright with that! Thanks man! :)

**Comment by Rndstad** [comment]
> I don't know how well the setEditable function works, but I do have a private repo where I have the 1.3.0 branch hosted which I use for my plugins. I don't know if @MinusKube is ok with that, that I share this:
> 
> ```
> <repository>
>   <id>sytm-nexus</id>
>   <url>https://repo.sytm.de/repository/maven-hosted/</url>
> </repository>
> ---
> <dependency>
>   <groupId>fr.minuskube.inv</groupId>
>   <artifactId>smart-invs</artifactId>
>   <version>1.3.0-SNAPSHOT</version>
> </dependency>
> ```
> 
> gn

Sometimes it is a bit buggy, but it is a whole lot better now. Sometimes I have to drop the item two times in the slot. Maybe you can take a look into that. 👍

**Comment by Rndstad** [comment]
Is there also a possibility to check the item you put in. Because I want only specific items to be accepted to drop in. @Sytm

**Comment by Sytm** [comment]
I am not sure, I didn't write the code for that. I am just building the latest commit of 1.3.0 and putting it up as a snapshot

**Comment by Rndstad** [comment]
oh alright, anyway thank you buddy!

**Comment by GitGraf** [comment]
I created a PR which should fix the issue concerning the `setEditable` API method.
