### ISSUE TITLE
Guava

### ISSUE THREAD

**Issue by Drc-DEV** [MinusKube/SmartInvs#105]
Can you remove the need for Guava as a dependency? It adds 1+Mb to the final jar and it's not really necessary for this library.

**Comment by portlek** [comment]
Hey, I guess we removed the whole bukkit dependency. But, 1.2.7 version has already bukkit dependency(also guava). The dependency removed from `master` branch. You can clone and install the project.

**Comment by Drc-DEV** [comment]
Thanks
