### ISSUE TITLE
How can I use a Anvil GUI?

### ISSUE THREAD

**Issue by KaylooYT** [MinusKube/SmartInvs#110]
How can I add and open an Anvil GUI?
`public static SmartInventory openAddFlagInventory(Player p) {		
		Region r = RegionManager.getRegion(RegionVar.editor.get(p).getName());
		return  SmartInventory.builder()
				.id("flagAddInventory")
				.type(InventoryType.ANVIL)
				.provider(new FlagProvider())
				.title("§cFlags §8- §c" + r.getName())
				.closeable(true)
				.build();
	}`

this is my code but it gets an npe

**Comment by Sytm** [comment]
Are you trying to get text input?

**Comment by KaylooYT** [comment]
> Are you trying to get text input?

yes

**Comment by Sytm** [comment]
Yeah, from this plugin you are only going to get pure click GUI stuff. If you want to get text-input have a look at this: [WesJD/AnvilGU](https://github.com/WesJD/AnvilGUI)

**Comment by KaylooYT** [comment]
Oh, okay. Thank you :D
