### ISSUE TITLE
help how to check if players opened inventory is example

### ISSUE THREAD

**Issue by Tanju42** [MinusKube/SmartInvs#111]
hey lets say i have a SimpleInventory named example

now how can I check if a players topInventory is example

I need it when i change the inventory that the players topInventory gest updated or does SmartInvs has a automatic Inventory updater on item change?

**Comment by Sytm** [comment]
> a automatic Inventory updater on item change

What do you mean by that?

To check if a inventory is opened by SmartInvs you can use this if you need to return the inventory.
```java
SmartInventory inv = SmartInvsPlugin.manager().getInventory(player).orElse(null);
if (inv != null && inv.getId().equals("idOfInventoryExample")) {
    return inv; 
}
return null;
```
But preferred variant is:
```java
SmartInvsPlugin.manager().getInventory(player).ifPresent(inv -> {
    if (inv.getId().equals("idOfInventoryExample")) {
        // Do stuff with inv here, or something else
    }
});
```

**Comment by Tanju42** [comment]
Thanks for the answer.

I mean by that if there is a Event or something that gets fired when something in the inventory gets changed like title a item ?
Example
a inventory with 1 item named Start and its an APPLE
so the player clicks on it the item gets changed in Starting...
this is easy but when something started like a Server i catch it and then I want to update the item to Started!
I thought abuot changeing the item to Started! but then the inventory wouldnt get updated
but also i dont want to use the update{} methode becouse it happens every tick and it would get very laggy

**Comment by Sytm** [comment]
I am gonna use a plugin of mine as an example here.

This is the class that implements the InventoryProvider interface: [WaypointsProvider.java](https://github.com/Sytm/waypoints/blob/master/src/main/java/de/md5lukas/wp/inventory/WaypointProvider.java).

---

As you can see, I init everything related to the inventory in `#init()` (the constructor is not that important here).

```java
@Override
public void init(Player player, InventoryContents inventoryContents) {
    viewer = player; // Save the player which has the waypoints open to this instance
    contents = inventoryContents; // Save the inventory contents for later to this instance
    waypoints = new PaginationList<>(waypointsPerPage); // plugin specific stuff, pagination helper
    rebuildWaypointsList(); // plugin specific stuff, creates the `ClickableItem`s for me
    page = 0; // plugin specific stuff, pagination helper
    setupOverview(); // sets the basic gui, like controls and stuff in the contents saved in the instance from above
    updateOverviewPage(); // this method updates the pagination stuff
}
```
Now every time the player clicks on the arrows for previous / next page `this.page` is updated and then `#updateOverviewPage()` is called to update the pagination *only* thanks to the reference to the original `inventoryContents` saved in the instance.

---

Pros (for this method):
 - It does not require an update every tick, only when the player does something.

Cons:
 - You **always** need to create a new instance of the `InventoryProvider`

---

I hope this is what you have looked for.

**Comment by Tanju42** [comment]
Thanks for the example I will try it and report back if its working but I think its not exactly the thing that I am  looking for 

by youre example the inv gets updated when the item gets clicked.

but I want to update the Inventory when some delayed task is finished and calls something like now();

and then the Inventory for the players that view it should get updated.

I hope I could explain it correctly and sry for my bad english I am from Germany

**Comment by Sytm** [comment]
Just add a method to your class and call it `pollData` for example. Then just actually poll the updated data and then update the inventory contents. 

or

Create a method and call it `serverUp` for example. Then just call it when you somehow get the info about the state change of the server and make it update the item X via the `InventoryContents`

---

> sry for my bad english I am from Germany

No problem, I am from Germany, too. (But we should keep it in English, so others, who perhaps have the same problem can understand).

**Comment by Tanju42** [comment]
Hey Sytm I have some specific questions and I would like to talk with you becouse I can't explain it here in the chat and in english
whe can talk on Skype(live:tanju42) or Discord(https://discordapp.com/invite/mSzBPwE)
