### ISSUE TITLE
SmartInvsPlugin.manager().getInventory(player).ifPresent NotWorking

### ISSUE THREAD

**Issue by Tanju42** [MinusKube/SmartInvs#113]
everytime I try to get the ID of the Inventory it prints an error with JavaLangNullPointerException
![SmartInvsError](https://user-images.githubusercontent.com/16364184/76360932-3bb35a80-631e-11ea-9895-e6dbab8a2d7c.png)

**Comment by MinusKube** [comment]
Hi, are you using SmartInvs as a standalone plugin or did you include it inside your jar?

**Comment by Tanju42** [comment]
I included it inside my jar here is how I initilaize it:
![image](https://user-images.githubusercontent.com/16364184/76365001-8f29a680-6326-11ea-949b-ad2273a6720a.png)

**Comment by MinusKube** [comment]
Okay, so you'll need to use the `inventoryManager` from your Main class instead of `SmartInvsPlugin.manager()`

**Comment by Tanju42** [comment]
Thanks alot I was going crazy becouse of this 
A note in the docs would be nice for people who have the same problem.

Really nice api btw keep up the good work 👍
