### ISSUE TITLE
New feature for SmartInventory

### ISSUE THREAD

**Issue by Emalios** [MinusKube/SmartInvs#114]
Can you add a method in the inventory builder so that the method: 
`void update(Player player, InventoryContents contents);`
depends on the tick time that we would have put in the builder, for example :
`updateTime(20);`
With default value 1 so as not to break old versions

**Comment by portlek** [comment]
there is already `updateFrequency` method in 1.3.0

**Comment by Emalios** [comment]
I did not see it in the documentation ^^

**Comment by MinusKube** [comment]
Yeah it's not in the docs since the 1.3.0 has not officially been released yet :p
