### ISSUE TITLE
Make ItemClickData#getEvent() less annoying to use

### ISSUE THREAD

**Issue by portlek** [MinusKube/SmartInvs#116]
I think ItemClickData is very useless class. Because It contains Event instead of InventoryClickEvent so, we have to make;
`final InventoryClickEvent clickEvent = (InventoryClickEvent) data.getEvent();`
I'm not using `from` method that's requesting `ItemClickData` because of that. I'm always using `of` method which's deprecated.

**Comment by MinusKube** [comment]
It's not useless, since we plan to be able to use SmartInvs from within InventoryClickEvent, but also PlayerInteractEvent, but we'll find a way to make this easier.

**Comment by MinusKube** [comment]
I guess a solution to this would be to add all the needed data into the ItemClickData class, in order to make the getEvent() call almost useless

**Comment by portlek** [comment]
> I guess a solution to this would be to add all the needed data into the ItemClickData class, in order to make the getEvent() call almost useless

Yea It's good idea. I liked that.

**Comment by Sytm** [comment]
You could also do it using dynamic types:
```java
public <T extends Event> getEvent() {
    return (T) event;
}
```

This is just out of memory and probably not 100% correct syntax

**Comment by portlek** [comment]
> You could also do it using generic types:
> 
> ```java
> public <T extends Event> getEvent() {
>     return (T) event;
> }
> ```
> 
> This is just out of memory and probably not 100% correct syntax

Actually, no. Because, a player can click to element with InventoryClickEvent and @MinusKube said it will also support for PlayerInteractEvent so, we must use `instanceof` to check what the actual event is. We can't use generic model for it.

**Comment by Sytm** [comment]
You can.
```java
InventoryClickEvent ice = x.getEvent();
PlayerInteractEvent pie = x.getEvent();
```
Both of these would work if the ItemClickData would contain the correct subclass of the Event class. It is the same as casting it yourself, but you don't need to actually do it.
