### ISSUE TITLE
Null event.getClickedInventory() bug.

### ISSUE THREAD

**Issue by portlek** [MinusKube/SmartInvs#118]
When a user has a item in the mouse cursor and if it click the green places;
![image](https://user-images.githubusercontent.com/12835420/76642990-4b70b000-6565-11ea-81ff-cd89a3ab6784.png)
event.getClickedInventory() is going to null and and an error comes about null point exception.

**Comment by portlek** [comment]
It can fix with
```java
if (event.getClickedInventory() == null) {
    return;
}
```
code to top of onInventoryClick method in InvListener class.

**Comment by MinusKube** [comment]
What line is causing the error?

**Comment by portlek** [comment]
Actually it's not for master or 1.3.0 branchs. It's for mine 1.3.0 pull requests that i opened. The issue is just for reminding to fix 
https://github.com/MinusKube/SmartInvs/pull/115/files#diff-08f5c1a765269763fcc11facdc1a5677R54
that line.
