### ISSUE TITLE
Improvement for listener(InventoryListener) method.

### ISSUE THREAD

**Issue by portlek** [MinusKube/SmartInvs#121]
I want to use that method without provider and with buttom inventory. For example;
```java
@NotNull
public SmartInventory inventory(@NotNull final Player player) {
    return SmartInventory.builder()
        .title(this.title.build(MapEntry.from("%player_name%", () -> player.getName())))
        .manager(DynamicShop.getAPI().inventoryManager)
        .size(this.size / 9, 9)
        .closeable(true)
        .id("quick-sell-page")
        .provider(new InventoryProvider() {
            @Override
            public void init(final Player player, final InventoryContents contents) {
            }

            @Override
            public void update(final Player player, final InventoryContents contents) {
            }
        })
        .listener(new InventoryListener<>(InventoryClickEvent.class, event -> {
            event.getWhoClicked().sendMessage("test");
        }))
        .build();
}
```
![image](https://user-images.githubusercontent.com/12835420/76852127-c2ef5980-685b-11ea-89ac-331266bab3bb.png)
I want to sell that with just click on it, but the inventory library can use with just top inventory. the `test` message don't come when I click the item in the buttom inventory. But It will be a good feature.

**Comment by portlek** [comment]
![image](https://user-images.githubusercontent.com/12835420/76852429-59bc1600-685c-11ea-83f1-4a84995bc36a.png)
This code is forbidding that feature.

**Comment by portlek** [comment]
Maybe buttomListener(InventoryListener) method can add for the `builder` with;
```java
if (clickedInventory.equal(buttomInventory)) {
    // TODO run buttom listener.
}
```

**Comment by Sytm** [comment]
So that would be same as #12
