### ISSUE TITLE
Issue regarding the docs.

### ISSUE THREAD

**Issue by officialrarlab** [MinusKube/SmartInvs#127]
Is there no docs at all currently? Something is wrong with gitbooks and I get redirected to a bad gateway form.

[Screenshot](https://gyazo.com/0711b1949675bd1221a3f9f20ebda33d)

**Comment by MinusKube** [comment]
It's just Gitbooks being down, next time this happens, use this link instead: https://web.archive.org/web/20200405155650/https://minuskube.gitbooks.io/smartinvs/
