### ISSUE TITLE
Is there a way for the player to put items in the GUI?

### ISSUE THREAD

**Issue by Coder-Iro** [MinusKube/SmartInvs#132]
I'm making custom crafting GUI with this plugin, But I realized that I couldn't put the item in the GUI made with this plug-in. How can the player put an item in the GUI?

**Comment by MinusKube** [comment]
Hello, this [feature](https://github.com/MinusKube/SmartInvs/issues/34) has been implemented in the 1.3.0 version which is not yet released (but you can still use it by building it yourself from the 1.3.0 branch).

I think you can also achieve this in the latest release by using the listeners and with some tweaking, but it might be quite difficult.
