### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by XXAOS** [MinusKube/SmartInvs#133]
I've been trying to get this to work forever and im new to java programming. Can someone help me out?
CONSOLE ERROR: https://pastebin.com/raw/wvtNL2w8
Project Structure:
![image](https://user-images.githubusercontent.com/42284153/81229458-b27a7600-8fa4-11ea-8f65-220c1b01c488.png)
EventHandle (Main Class): https://pastebin.com/raw/N9BgvqDP
SimpleInventory (Straight from the docs): https://pastebin.com/raw/Nitc17pe
Open Inventory Command: https://pastebin.com/raw/nw9QM9j1

Plugin yml: https://pastebin.com/raw/fmB1Lx9K

**Comment by XXAOS** [comment]
Putting the plugin in the PLugin folder aswell seemed to have solved the issue

**Comment by XXAOS** [comment]
I got no fucking clue how to set this to solved never used github lol

**Comment by MinusKube** [comment]
Just close the issue, but I'll do it :p
