### ISSUE TITLE
Want to make dynamic content of custom ui

### ISSUE THREAD

**Issue by kate-gg** [MinusKube/SmartInvs#134]
Hi i need help with dynamic content
so i have HashMap that contain information I want to use
to open custom UI you have to right click on furnace to open it
furnace have custom data that contain in HashMap
how do I display data to UI that use HashMap on specify furnace
--
if you don't understand I can make flowchart for you

**Comment by portlek** [comment]
Can you explain more, maybe i can do it on my fork

**Comment by kate-gg** [comment]
So method i use is get player target block that work
but i need something like send value from open inventory class to inventory builder

**Comment by portlek** [comment]
there is a property method, did you check it?

**Comment by kate-gg** [comment]
can you give me a link of doc or example?
(sorry for replay so lately)

**Comment by portlek** [comment]
https://github.com/MinusKube/SmartInvs/blob/1.3.0/src/main/java/fr/minuskube/inv/content/InventoryContents.java#L485
and
https://github.com/MinusKube/SmartInvs/blob/1.3.0/src/main/java/fr/minuskube/inv/SmartInventory.java#L66
these methods will be helpful for your situation.
