### ISSUE TITLE
How to set armor items in a InventoryType.PLAYER inventory ?

### ISSUE THREAD

**Issue by Croos3r** [MinusKube/SmartInvs#140]
I'm trying to make an invsee command where I display a player inventory (obvious ^^)
But I don't know how to set the armor items.

**Comment by MinusKube** [comment]
The inventory type PLAYER is not supported by default in SmartInvs, you can try making a custom 
InventoryOpener for this (not sure if really possible with Minecraft limitations), then if you set the inventory size as "1 row and 41 columns", you should be able to set the slots as shown below:
![image](https://user-images.githubusercontent.com/13206601/84577116-c42c1600-adb9-11ea-895d-13e913af46bb.png)
