### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by XXAOS** [MinusKube/SmartInvs#143]
GUI Code
![image](https://user-images.githubusercontent.com/42284153/85911538-b4a9c580-b7da-11ea-88d1-a79b88640302.png)
Main code:
![image](https://user-images.githubusercontent.com/42284153/85911552-be332d80-b7da-11ea-862d-2416a43e6276.png)
Error:
![image](https://user-images.githubusercontent.com/42284153/85911567-c9865900-b7da-11ea-878c-94b696c72c42.png)

**Comment by MinusKube** [comment]
Hi, you need to export SmartInvs inside your plugin's JAR, or to add it as a plugin on the server.

**Comment by XXAOS** [comment]
Thanks, it works 👍

**Comment by XXAOS** [comment]
Amazing API by the way.
