### ISSUE TITLE
SmarInvs Lib override my plugin

### ISSUE THREAD

**Issue by uiytt** [MinusKube/SmartInvs#145]
Hi,
I'm using 1.14.4-R0.1-SNAPSHOT with SmartInvs 1.2.7 as a Library inside my Plugin and maven as a build system.
When I build my plugin without SmartInvs in it, everything works fine but if my plugin is build with SmartInvs in it,
 when spigot launch, it only detect SmartInvs and my plugin doesn't work at all. 

Creating a InventoryManager and using init() doesn't change anything.
Does someone know why it happens ? 
Thanks

**Comment by portlek** [comment]
you can use maven-shade-plugin with relocation feature.

**Comment by uiytt** [comment]
So I just shade fr.minuskube.inv to fr.minuskube.shade.inv  ?

**Comment by uiytt** [comment]
I found the problem, the plugin.yml from SmartInvs override mine when I put it in my jar with maven :/

**Comment by MinusKube** [comment]
I think you can exclude this file with the maven shade plugin

**Comment by uiytt** [comment]
I don't think so but I will soon switch to gradle and I know it possible with gradle.
Anyway, thanks, you should probably mention it somewhere
