### ISSUE TITLE
Difficulties adding api to my plugin

### ISSUE THREAD

**Issue by 6u5t4v** [MinusKube/SmartInvs#146]
I am using maven so I have added the dependency too my pom.xml, and initalized variable:
![image](https://user-images.githubusercontent.com/41763143/86638453-9bbdc300-bfd7-11ea-9b2c-7a36d2b7fdea.png)
Before I build inventories I call the Init() method from the inventoryManager, which is added to the builder:
![image](https://user-images.githubusercontent.com/41763143/86638567-c90a7100-bfd7-11ea-822a-3de00194e4be.png)
Not really sure what else I can do

**Comment by 6u5t4v** [comment]
![image](https://user-images.githubusercontent.com/41763143/86638626-e9d2c680-bfd7-11ea-8c8f-2b91cdd0636d.png)

**Comment by portlek** [comment]
what the actual problem is?

**Comment by 6u5t4v** [comment]
oh yeah xD, I am getting this when the plugin loads
https://pastebin.com/vPGeecWj

**Comment by 6u5t4v** [comment]
I am using spigot version 1.16.1

**Comment by portlek** [comment]
your jar or your server has not smart inventory dependency

**Comment by 6u5t4v** [comment]
It should have.
Added like the jar
![image](https://user-images.githubusercontent.com/41763143/86651782-1bea2580-bfe4-11ea-83f3-571eb811baba.png)
aswell as added it as a dependency in the pom
![image](https://user-images.githubusercontent.com/41763143/86651920-3ae8b780-bfe4-11ea-8883-b97fb54d2b05.png)

**Comment by portlek** [comment]
show the whole pom.xml file

**Comment by 6u5t4v** [comment]
https://pastebin.com/shhN5RbT

**Comment by 6u5t4v** [comment]
I am trying to avoid having the plugin inside the plugins folder

**Comment by portlek** [comment]
addd maven-shade-plugin to your pom.xml

**Comment by 6u5t4v** [comment]
Are there some specific settings I need to do?

**Comment by 6u5t4v** [comment]
That seemed to have fixed it thank you :)

**Comment by portlek** [comment]
@MinusKube close it.
