### ISSUE TITLE
Item Name

### ISSUE THREAD

**Issue by Nikotecnology** [MinusKube/SmartInvs#166]
Hi, i was tryng to make a gui with this api but i can't find the method to assign a item display name how i can do?

**Comment by Paul2708** [comment]
You have to pass an [`ItemStack`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemStack.html), therefore, just assign it on your own using [`ItemMeta#setDisplayName`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#setDisplayName(java.lang.String)).

**Comment by Nikotecnology** [comment]
yes, but there isn't a simplyfied method? Because i don't want so much code for setting a display name

**Comment by MinusKube** [comment]
Not within SmartInvs, but you can use any ItemBuilder lib you want

**Comment by Matix-Media** [comment]
A good Item builder I could recommend: https://pastebin.com/1XSLn1Ps
