### ISSUE TITLE
Problems using the api

### ISSUE THREAD

**Issue by thefrogline** [MinusKube/SmartInvs#189]
Hello!; I've been trying to use this api for several days, but when trying to use maven shading, it doesn't work for me, but if I put the api in the plugins folder it works for me, but I would like to have it in the same jar everything, you could tell me how do this ?, currently I have my pom like this:
https://pastebin.com/kVzzZVAB

, if you help me, I would be very grateful, recently I am working with maven and I do not understand
![image](https://user-images.githubusercontent.com/76601496/121924747-ca710d00-cd01-11eb-9170-b9210d7d9b3e.png)
 much what to do.

**Comment by portlek** [comment]
![image](https://user-images.githubusercontent.com/12835420/121925264-68d29200-cd45-11eb-942d-602447ac6496.png)

**Comment by thefrogline** [comment]
I guess I am using the api wrong, and the error is from the first error? "The SmartInventory.Builder administrator must be configured!", So if it works for me with the api in the plugins folder, but I don't want that, or is there no other way?

**Comment by portlek** [comment]
check this class 
https://github.com/MinusKube/SmartInvs/blob/master/src/main/java/fr/minuskube/inv/SmartInvsPlugin.java

**Comment by thefrogline** [comment]
omg, thank you very much, it worked for me, I was so attentive to the shade that I thought I was doing it wrong, but that was it, thank you very much ^^
