### ISSUE TITLE
add function

### ISSUE THREAD

**Issue by wuming123** [MinusKube/SmartInvs#2]
I hope the next version can enhance the players under the inventory of interactive

When I want to use this API to create a warehouse for players to store items
I can not start

Should be given developer close event and Cancelled processing

**Comment by MinusKube** [comment]
I'm not sure to understand what you want. You want a way to have access to the inventory events (click event, close event, etc...)?

**Comment by wuming123** [comment]
I hope I can control Cancel

**Comment by MinusKube** [comment]
(Sorry for the late answer) You can already quite control it using the `SmartInventory.Builder#listener(InventoryListener)` method.

**Comment by wuming123** [comment]
You are late for too long!
I have solved this problem!
I modified this framework locally!
