### ISSUE TITLE
Updating ItemMeta without replacing the actual Item.

### ISSUE THREAD

**Issue by crysis992** [MinusKube/SmartInvs#20]
I currently stuck with a problem using the update method from the InventoryProvider.

I have a cooldown running on my kits that are displayed inside the GUI, now I want a visual countdown, but somehow I didn't figure out how to update the lore or ItemMeta in general for a ClickableItem without replacing it completely. 
Is there some way to update the ItemMeta for a specific slot without replacing the item completely?

That's what I've tried so far:
```
@Override
	public void update(Player player, InventoryContents contents) {
		
	    int state = contents.property("state", 0);
	    contents.setProperty("state", state + 1);

	    if(state % 10 != 0)
	        return;

	    
	    CorePlayer cp = Core.getPlugin().getCorePlayer(player);
	    
	    contents.get(1, 2).ifPresent(item -> {
	    	
	    	
	    	Optional<Kit> kit = addon.getKit(item.getItem().getItemMeta().getDisplayName());
	    	
	    	if (!kit.isPresent()) {
	    		return;
	    	}
	    		    	
	    	ItemStack i = item.getItem();
	    	ItemMeta meta = i.getItemMeta();
	    	List<String> lore = meta.getLore();
	    	
	    	
	    	if (lore.size() > 0 && lore.get(0) != null && lore.get(0).startsWith("§7Cooldown")) {
	    		lore.set(0, "§7Cooldown: " + UtilTime.convertString(cp.getRemaingKitTime(kit.get().getName()), 2, net.crytec.api.util.UtilTime.TimeUnit.FIT));
	    		meta.setLore(lore);
	    		i.setItemMeta(meta);
	    		System.out.println("Lore Updated");
	    	}	    	
	    });
		
		
	}
```

The debug messages shows up, also the ItemMeta inside the Clickable Item does get changed, but it's not updating in the inventory view

**Comment by MinusKube** [comment]
Maybe try to add: `contents.set(1, 2, item);` at the end, in order to update the bukkit inventory, but I'll think I'll add a way in 1.3.0 to clone a ClickableItem so we can change the ItemStack and keep the same Consumer.
