### ISSUE TITLE
Do I need to register anything for the clickable items to work?

### ISSUE THREAD

**Issue by tjark-staedtler** [MinusKube/SmartInvs#206]
Do I need to register anything for the clickable items to work?

**Comment by MinusKube** [comment]
Hi, if you're putting SmartInvs directly as a plugin, you have nothing to do, besides using the clickable items correctly, inside a SmartInventory, like shown in the Gitbook examples. But if you're exporting SmartInvs inside your own plugin jar, you need to initialize an InventoryManager and call the `init()` method on it, inside your plugin's `onEnable()`, then pass this manager as argument to the `.manager(...)` method when building an inventory.

Here's an example: https://github.com/MinusKube/SmartInvs/issues/191#issuecomment-914487546

**Comment by tjark-staedtler** [comment]
Okay, i made it right you said, but it didn*t work?

**Comment by MinusKube** [comment]
What is happening? The items appear in the inventory but when you click them nothing happens?
