### ISSUE TITLE
[Idiot] Having a bit of trouble with the GUI after the update.

### ISSUE THREAD

**Issue by TerraPrimal** [MinusKube/SmartInvs#22]
So I was few versions behind (1.1.3) and I have updated and added the new InventoryManager, however I still can't get it to work.
The GUI loads fine and doesn't override the borders (thanks for that) but there is no response from the icons or the pagination prev, next.
I guess I am missing something obvious and need it spelt out for me -_-.

I had added a .gif below and a snippet of code (just basic pagination).
https://i.gyazo.com/3fab7832db51e9c1b745fd3c70e9be20.gif
https://pastebin.com/ehXMFUyM

Thanks!

**Comment by TerraPrimal** [comment]
I have also tried having the following in my MenuClass
https://pastebin.com/tJQRKUXx

And this is my main class
https://pastebin.com/NWxsA007

The SmartInvs-1.2.1.jar is in my plugins folder as well as depend: [SmartInvs]
The above method throws this error: https://pastebin.com/DGGdutXU

**Comment by MinusKube** [comment]
Hi, you must call the `invManager.init()` method before using it :p

**Comment by TerraPrimal** [comment]
Of bloody course, in my code I am registering my listener class PRIOR to init the InventoryManager... ofc it throws an error...

Thank god this moment of idiocy isn't publicly view-able, for like... ever :D

**Comment by Rndstad** [comment]
It is ‘publicly view-able’ @TerraPrimal
