### ISSUE TITLE
Question about listeners

### ISSUE THREAD

**Issue by crysis992** [MinusKube/SmartInvs#23]
Since I didn't find anything in the documentation, I'll open a ticket here.
Could you explain to me how to add a listener? I need to execute some code once a SmartInventory was closed. I know the builder has a listener method, but I don't understand how to use it properly.

A small example would be really helpful.
What I'm trying to do:
The player opens the GUI -> ItemStack from his main hand goes to slot 0 in the GUI -> When the player closes the GUI it should be returned to their main hand. But I don't get how to use the listener method inside the builder.

**Comment by MinusKube** [comment]
Ohhh, there is no example of this in the docs, I should add one.
Here is a small example:
```java
SmartInventory inventory = SmartInventory.builder()
    .provider(...)
    .listener(new InventoryListener(InventoryCloseEvent.class, event -> {
        // ...
    }))
    .build();
```

**Comment by crysis992** [comment]
Thanks, that solves my problem.
