### ISSUE TITLE
Error by opening GUI

### ISSUE THREAD

**Issue by Rndstad** [MinusKube/SmartInvs#25]
Hello MinusKube! 

I'm now using your inventory API, but I got an error by opening GUI.
I use it as a library so I have initialised it in my main class (Core).

This is the error:
https://hastebin.com/jepimamapo.apache

This is my Core class:
https://hastebin.com/hehujipile.java

And I'm using the exact same class on your tutorial SimpleInventory.

I hope you could help me! 

Regards,
Rndstad

**Comment by MinusKube** [comment]
Do you use a CraftBukkit server or a Spigot one?

**Comment by MinusKube** [comment]
Okay after some tests, it is clearly an issue from SmartInvs which is present on all 1.8.8 servers, I'll release 1.2.3 to fix that :)

**Comment by Rndstad** [comment]
Awesome MinusKube!
