### ISSUE TITLE
Closeable

### ISSUE THREAD

**Issue by Rndstad** [MinusKube/SmartInvs#26]
Do you know how to change the 'closeable' to true, I had set it to false but when a player press on the green or red wool block I want to set the closeable boolean to true to close the inventory from the player.

**Comment by MinusKube** [comment]
Oh, I'm afraid it's not really currently possible without opening another inventory, I'll fix that soonly by adding a SmartInventory#setCloseable(boolean) method :p

**Comment by Rndstad** [comment]
That’ll be awesome! Thank you!

**Comment by Rndstad** [comment]
Hello MinusKube,
How to change the closeable statement in the existing init method with your new update?

**Comment by MinusKube** [comment]
Hi, just use `contents.inventory().setCloseable(true)` for example :)

**Comment by Rndstad** [comment]
Awesome! Thank you very much! ❤️
