### ISSUE TITLE
Inventory per Player

### ISSUE THREAD

**Issue by 12XpresS12** [MinusKube/SmartInvs#30]
Hello, I had a big problem with Inventory per player, when I updating a inventory and somebody open the inventory on same time. He sees same contents as I.

Can you repair this thing, please ?

**Comment by MinusKube** [comment]
Can you show me your code please?

**Comment by 12XpresS12** [comment]
Its my mistake, I did it as U have in documantations
```
public SmartInventory dailyGui = SmartInventory.builder()
	        .id("dailyGui")
	        .provider(new DailyProvider())
	        .size(3, 9)
	        .title("§8§lDenné odmeny")
	        .closeable(true)
	        .build();
```

 I had this as static method, and then did this.
