### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by BetaPlays3** [MinusKube/SmartInvs#35]
Inventories are for all players.

For example: One player opens the inventory, then another opens the same inventory, the second player controls the forward and backward pages of all players

So:
SmartInv.open (player, pagination) not working

Only works if I do a HashMap <Player, SmartInventory>

**Comment by MinusKube** [comment]
Aaaaand, it's fixed, 1.2.6 has just been released, thank you! :)
