### ISSUE TITLE
Critical Bug - Per player inventories not working

### ISSUE THREAD

**Issue by crysis992** [MinusKube/SmartInvs#36]
This is kinda a critical bug, since it totally breaks the whole api/plugin.

I have a static variable of the SmartInventory:
`
	public static final SmartInventory REGION_HOME = SmartInventory.builder().id("regiongui.home")
				.provider(new LandHomeMenu())
				.size(6, 9)
				.title(Language.INTERFACE_HOME_TITLE.toString())
				.build();
`

InventoryProvider for the REGION_HOME: https://pastebin.com/ihtNr7He

I'm using REGION_HOME.open(player) -> Each player should see their own instance/inventory.
But:
Player 1 opens their home gui -> Works
If player2 opens their home gui while player1 has still the inventory open -> Player 1 sees the content from player2 and has all ClickableItems from player2.
Same for more than 2 players.

Video: https://www.youtube.com/watch?v=0-_J4GE8oxw

All players will only see the contents from the last opened inventory, that makes it impossible to add per-player icons/text or whatever to the ClickableItems

I guess that relates to: #35 

Since this is a kinda critical bug, I hope that it's fixed as soon as possible, because I'm using this in more than 40+ private and public plugins.

**Comment by crysis992** [comment]
With this change I'm getting ArrayIndexOutOfBoundsException with Inventories that contains more than 4 Items. https://pastebin.com/VvD61wdN

I already figured out the cause:
At some state (not always) the topInventory inside the update method of InventoryContents is of the type CRAFTING -> Means the player does not have an open top/inventory. This happens during the init phase.

**Comment by MinusKube** [comment]
Hi, thank you for the testing and the report :p I'll try to fix that ASAP

**Comment by MinusKube** [comment]
Aaaaand, it's fixed, 1.2.6 has just been released, thank you! :)
