### ISSUE TITLE
No way to close inventory on Inventory GUI Provider

### ISSUE THREAD

**Issue by U-siro** [MinusKube/SmartInvs#37]
No way to close inventory on Inventory GUI Provider

**Comment by MinusKube** [comment]
Hi, there is a way to do this, it's `contents.inventory().close(player)` :)

**Comment by TheFlash787** [comment]
Hey! If that doesn't work ^ (if it's not what you're looking for), ensure that `.closable()` is set to true in `SmartInventory#builder()`

**Comment by U-siro** [comment]
Thanks!
