### ISSUE TITLE
Feature Request - Open Menu with Custom Name

### ISSUE THREAD

**Issue by DankPrison** [MinusKube/SmartInvs#43]
I've hit a few limitations of your API that I feel should be adjusted to enhance usability and customization of title in menus.
Add ability to set menu title in the same line you open the menu for the player instead of being forced to set it inside the builder method in the menu with limits customization.
what I'm proposing is instead of lets say

SettingsMenu.INVENTORY.open(player)

to open the inventory for player with a set title that cannot have input from player in the title to

SettingsMenu.INVENTORY.open(player, "Settings of "+player.getName())

that way you can have more expand-ability in the menu title department cause it's severely lacking. Cause this is not possible in your current API without making a map and setting to before you open menu, and it runs into some weird issues I'm not sure if menu titles are cached or something but it refused to change once initially set even though variable was clearly changing.

**Comment by MinusKube** [comment]
Hi, you can do this by creating the builder each time you want to open the inventory. There is an example inside the docs, in the section "Context-dependant Example": https://minuskube.gitbooks.io/smartinvs/pages/getting_started.html#context-dependent-example

**Comment by DankPrison** [comment]
@MinusKube I see Thank You.
