### ISSUE TITLE
Mouse resets to center when opening new inventory in 1.7

### ISSUE THREAD

**Issue by MinusKube** [MinusKube/SmartInvs#48]
When we open a new inventory in 1.7, the mouse resets to the center of the screen, this is due to the 1.7, but there is a possible workaround if we replace the current inventory contents instead of opening a new one.

**Comment by DevSnox** [comment]
Are you sure, that you still want to support 1.7?

**Comment by LartyHD** [comment]
This is still the case in 1.8

**Comment by DevSnox** [comment]
Oh i didn't now that.

**Comment by MinusKube** [comment]
Yes, I want to keep support for the 1.7 version, and I don't think I've encountered this bug when I tested in 1.8, but I'll check again

**Comment by MinusKube** [comment]
Update: This only happens for 1.7 **servers**, the client version doesn't matter.

**Comment by LartyHD** [comment]
I check it with an 1.8.8 Spigot Server and an 1.8.8 Client

**Comment by DrPanic** [comment]
Still an Issue with 1.13.2 Paper Server and Version 1.2.7

**Comment by MinusKube** [comment]
@DrPanic Mhhh I tested with 1.13.2 b624 Paper Server and couldn't reproduce the issue, maybe check you donn't close the old inventory before opening the new one and maybe give more info

**Comment by MinusKube** [comment]
I'm closing this as I'm unable to reproduce the issue with recent versions, and I'm not willing to develop a workaround for a minor bug of a version released almost 7 years ago.
