### ISSUE TITLE
NoClassDefFoundError: org/bukkit/plugin/Plugin when using Paper 1.9.4 (Build #773)

### ISSUE THREAD

**Issue by TheMelvinNL** [MinusKube/SmartInvs#52]
When using the constructor of the InventoryManager: `new InventoryManager(this)` in the `onEnable()` method of my plugin. I get a NoClassDefFoundError. 

I'm using PaperSpigot build #773 for 1.9.4. I already contacted the Paper support team and they do not know what is going on. Other plugins work fine too, only my plugin with SmartInvs produces this error.

**Edit:** The same error occurs when using the SmartInvs standalone plugin.

**Comment by MinusKube** [comment]
I don't think I can do anything for this, the issue must be related to your PaperSpigot build, which must be, like... Broken or something 🤔

**Comment by TheMelvinNL** [comment]
It makes no sense, SmartInvs doesn't do weird or hacky things.
I'll see what I can do to fix it, and comment here with the result, so others won't have any problems with this.

**Comment by TheMelvinNL** [comment]
Ah, got it. When using PaperSpigot, you should **not** use `-cp` as startup parameter.
PaperSpigot does some weird things with the patching the jar files and that's what caused an issue with the classes. When using `-jar <the-jar>` it works fine.

I still have no clue why other plugins worked fine, and SmartInvs didn't. Might have something to do with the dependencies that were loaded in my plugin (via the classpath parameter).

Thanks for your help anyway 😝
