### ISSUE TITLE
Problem with open Inventory

### ISSUE THREAD

**Issue by LynSisCZ** [MinusKube/SmartInvs#53]
Hello i have a problem with open inventory on my function list() 
i call a ModreqList.INVENTORY.open(player);

[ModreqAdmin](https://hastebin.com/masigedime.java)

I use Maven with : 
https://hastebin.com/cikosoloci.xml

Code:
https://hastebin.com/movahazogu.java

ERROR
https://hastebin.com/arixafigut.php

**Comment by MinusKube** [comment]
Hello, you must either use SmartInvs as a plugin on your server, or add a `.manager(invManager)` to your builder:
![image](https://user-images.githubusercontent.com/13206601/54390794-9e3e3000-46a3-11e9-85ba-02b952c92fef.png)

**Comment by LynSisCZ** [comment]
Omg, thanks :)
