### ISSUE TITLE
Make Clickableitem moveable... & InventoryCloseEvent

### ISSUE THREAD

**Issue by nxtVentix** [MinusKube/SmartInvs#54]
Hello,

1. I would like to know, how can i make the ClickableItem moveable.

I currently use the snippets to test smartinvs.
https://minuskube.gitbooks.io/smartinvs/

2. is there a inventorycloseevent? or should i use this from bukkit?

**Comment by MinusKube** [comment]
1. You currently can't, unless you manage to do some tricking using the Bukkit events and their priority.

2. When building a SmartInventory, you can provider a `.listener(...)` which allow you to listen to some events related to this inventory, including the `InventoryCloseEvent`, example:
```java
SmartInventory.builder()
        ...
        .listener(new InventoryListener(
            InventoryCloseEvent.class,
            event -> {
                Player player = (Player) event.getPlayer();
                player.sendMessage("You closed the inventory! Well played!");
            }
        )
        .build();
```

**Comment by nxtVentix** [comment]
Oh okayy thank you.

**Comment by MinusKube** [comment]
(I forgot to specify, but for the question `1`, it's planned to be possible in the future, if you want to see the advancement for it, there is an issue opened for it: https://github.com/MinusKube/SmartInvs/issues/34)
