### ISSUE TITLE
Animation does not work

### ISSUE THREAD

**Issue by TheDarkCookiee** [MinusKube/SmartInvs#58]
93/5000
 I have tried the example with the animations but unfortunately the animation does not work.
Do I have to update or add init method where else?

// ItemStack glass = new ItemStack(Material.GLASS_PANE, 1, durability);
ItemStack constructor is deprecated
Version 1.13

`   public static final SmartInventory INVENTORY = SmartInventory.builder()
            .id("myInventory")
            .provider(new SimpleInventory())
            .size(3, 9)
            .title(ChatColor.BLUE + "My Awesome Inventory!")
            .build();

    private final Random random = new Random();

    @Override
    public void init(Player player, InventoryContents contents) {
        contents.fillBorders(ClickableItem.empty(new ItemStack(Material.GLASS_PANE)));

        contents.set(1, 1, ClickableItem.of(new ItemStack(Material.CARROT),
                e -> player.sendMessage(ChatColor.GOLD + "You clicked on a potato.")));

        contents.set(1, 7, ClickableItem.of(new ItemStack(Material.BARRIER),
                e -> player.closeInventory()));
    }

	@Override
    public void update(Player player, InventoryContents contents) {
        int state = contents.property("state", 0);
        contents.setProperty("state", state + 1);

        if(state % 5 != 0)
            return;

        short durability = (short) random.nextInt(15);

        ItemStack glass = new ItemStack(Material.GLASS_PANE, 1, durability);
        contents.fillBorders(ClickableItem.empty(glass));
    }
}
`

MainClass   `public void onEnable() {
		   plugin = this;
		   InventoryManager m = new InventoryManager(plugin);
		   m.init();`
                   }

MyGameModeClass   SimpleInventory.INVENTORY.open(p);

**Comment by MinusKube** [comment]
Hi, can you send a screen/gif of what's happening to your inventory?

**Comment by TheDarkCookiee** [comment]
http://prntscr.com/nmzqs3

**Comment by MinusKube** [comment]
Do you have any error in the console?

**Comment by Sytm** [comment]
If it's still relevant:
Looks like you are using it as a dependency because you create your own InventoryManager your main class. But you still need to set this custom manager while creating your SmartInventory.
```java
public static final SmartInventory INVENTORY = SmartInventory.builder()
.id("myInventory")
.provider(new SimpleInventory())
.size(3, 9)
.title(ChatColor.BLUE + "My Awesome Inventory!")
.manager(m) // <-- This one is missing in your provided code
.build();
```
In case you use it as a plugin, you can leave this out:
```java
public void onEnable() { 
    plugin = this;
    InventoryManager m = new InventoryManager(plugin);
    m.init();
}
```
And you don't need to set a custom manager
