### ISSUE TITLE
Add contents#fillSquare() method

### ISSUE THREAD

**Issue by DevSnox** [MinusKube/SmartInvs#59]
Should be self explaining.
Would be very nice to have more shapes as fill possibilities.

I hope it's understandable.

**Comment by MinusKube** [comment]
I'm not sure it would really be useful since there is already a `fillRect` method

**Comment by DevSnox** [comment]
But the fillRect method only fills the borders.
In my opinion, it's useful.

**Comment by MinusKube** [comment]
Oh, yes, you're right!
