### ISSUE TITLE
Setup  item page

### ISSUE THREAD

**Issue by leM7mdx** [MinusKube/SmartInvs#63]
I can't add an item with String in config` @Override
    public void init(Player player, InventoryContents contents) {
      

        Pagination pagination = contents.pagination();
        ClickableItem[] items = new ClickableItem[600];
        int i;
        for (i = 0; i < items.length; i++) {
            for (String s : Main.getInstance().fileManager.Servercfg.getStringList("Permissions")) {
                ItemStack itemStack = new ItemStack(Material.TNT, 1);
                ItemMeta meta = itemStack.getItemMeta();
                meta.setDisplayName(s);
                List<String> loreList = new ArrayList<String>();
                loreList.add("ID" + i);
                meta.setLore(loreList);
                itemStack.setItemMeta(meta);
                items[i] = ClickableItem.empty(itemStack);
                pagination.setItems(items);
                pagination.setItemsPerPage(27);

                pagination.addToIterator(contents.newIterator(SlotIterator.Type.HORIZONTAL, 0, 0));

                contents.set(3, 7, ClickableItem.of(new ItemStack(Material.ARROW), e -> INVENTORY.open(player, pagination.previous().getPage())));
                contents.set(3, 8, ClickableItem.of(new ItemStack(Material.ARROW), e -> INVENTORY.open(player, pagination.next().getPage())));
            }
        }
    }`

video
https://media.giphy.com/media/ZBtYLTVKn7zkHfAMgO/giphy.gif

**Comment by Sytm** [comment]
Could you please explain further, what you are trying to do and what doesn't work? Because the video you provided is very blurry and only has a resolution of 480 x 270 px.

Even if the code isn't really clear to me, I would recommend putting this after your for loops, as it would just be unnecessary after the first iteration from what I understand:
```java
pagination.setItems(items);
pagination.setItemsPerPage(27);

pagination.addToIterator(contents.newIterator(SlotIterator.Type.HORIZONTAL, 0, 0));
contents.set(3, 7, ClickableItem.of(new ItemStack(Material.ARROW), e -> INVENTORY.open(player, pagination.previous().getPage())));
contents.set(3, 8, ClickableItem.of(new ItemStack(Material.ARROW), e -> INVENTORY.open(player, pagination.next().getPage())));
```

**Comment by leM7mdx** [comment]
https://www.youtube.com/watch?v=VgQLOvy4sMk&feature=youtu.be

I want to get the names form StringList and put it in the item

but I have an issue in my code  he gets the last name and put as you can see in the video

**Comment by Sytm** [comment]
Ahh, I see. I think it comes from your nested for loops.

Something like this should do the trick (Untested, could contain syntax errors because I just changed it in Notpad++):
```java
@Override
public void init(Player player, InventoryContents contents) {

	Pagination pagination = contents.pagination();
	
	List<String> permissions = Main.getInstance().fileManager.Servercfg.getStringList("Permissions");
	ClickableItem[] items = new ClickableItem[permissions.size()]; // Setting the size to the size of permissons to reduce unused array elements
	
	for (int i = 0; i < items.length; i++) { // Just one for loop
		ItemStack itemStack = new ItemStack(Material.TNT, 1);
		ItemMeta meta = itemStack.getItemMeta();
		
		meta.setDisplayName(permissions.get(i));
		
		List<String> loreList = new ArrayList<String>();
		loreList.add("ID" + i);
		meta.setLore(loreList);
		
		itemStack.setItemMeta(meta);
		items[i] = ClickableItem.empty(itemStack);
	}
	
	pagination.setItems(items); // Move this to the end, because performance and stuff. If you keep it in the loop, you'll just override it over and over again
	pagination.setItemsPerPage(27);

	pagination.addToIterator(contents.newIterator(SlotIterator.Type.HORIZONTAL, 0, 0));

	contents.set(3, 7, ClickableItem.of(new ItemStack(Material.ARROW), e -> INVENTORY.open(player, pagination.previous().getPage())));
	contents.set(3, 8, ClickableItem.of(new ItemStack(Material.ARROW), e -> INVENTORY.open(player, pagination.next().getPage())));
}
```

**Comment by leM7mdx** [comment]
OMG, that's why, Thank you so much for helping me.

**Comment by Sytm** [comment]
You're welcome!
