### ISSUE TITLE
Make inventory default's size dependent on selected type

### ISSUE THREAD

**Issue by MinusKube** [MinusKube/SmartInvs#68]
The inventory default's size is currently independent from the selected inventory type, whatever the type is, the size will be 6 rows and 9 columns, but this would be better, when no size is manually specified, to get the default size for all the inventory types, so it doesn't cause any problem when using SlotIterators, patterns, and similar things.

**Comment by MinusKube** [comment]
TODO: Allow InventoryOpeners to define their own default sizes for supported types

**Comment by GitGraf** [comment]
InventoryOpeners can now override the method `defaultSize(InventoryType)` to provide custom defaults for supported types. 
If the method is not overridden, the default implementation is used, which behaves like this:

 - CHEST and ENDER_CHEST size = 3 x 9
 - DROPPER and DISPENSER size = 3 x 3
 - anything else will just be 1 x `type.getDefaultSize()`

**Comment by GitGraf** [comment]
can be closed
