### ISSUE TITLE
Add way to choose at which frequency the update method is called

### ISSUE THREAD

**Issue by MinusKube** [MinusKube/SmartInvs#75]
The update method is currently called every tick, it would be better to have something to choose at which frequently is called, maybe with an annotation like `@UpdateFrequency(20)`, or maybe with a `.updateFrequency(20)` method in the builder.

**Comment by GitGraf** [comment]
Created pull request #78.

**Comment by Poslovitch** [comment]
This should be closed since it has been since implemented.

**Comment by GitGraf** [comment]
Should possibly also be mentioned in the GitBook documentation somewhere.

**Comment by MinusKube** [comment]
When the 1.3.0 will be released, I'll update the GitBook accordingly to all the new features :) (And most of the GitBook will be rewritten too)
