### ISSUE TITLE
Help Inv not open

### ISSUE THREAD

**Issue by nahubar** [MinusKube/SmartInvs#77]
`            public static final SmartInventory INVENTORY = SmartInventory.builder()
            .id("Inventario")
            .provider(new SimpleInventory())
            .size(3, 9)
            .type(InventoryType.CHEST)
            .closeable(false)
            .title(ChatColor.BLUE + "Inventario")
            .build();
            
    @Override
    public void init(Player player, InventoryContents c) {
        for(int i = 0; i < 9; i += 2){
        
       c.fillColumn(i, ClickableItem.empty(new ItemStack(BEDROCK)));
       SimpleInventory.INVENTORY.open(player);
               }
        
    }

    @Override
    public void update(Player player, InventoryContents c) {
      SimpleInventory.INVENTORY.open(player);
    }`
This is my code and my inventory not open, what am I doing wrong?

**Comment by MinusKube** [comment]
The open method must be called when you want your inventory to be opened

**Comment by nahubar** [comment]
SimpleInventory.INVENTORY.open(player);?

**Comment by MinusKube** [comment]
Yes

**Comment by nahubar** [comment]
Ok, but for the SimpleInventory.INVENTORY.open (p);
I need to get the player somehow but I don't have a method to get it, what could I do?

**Comment by nahubar** [comment]
.

**Comment by GitGraf** [comment]
@nahubar I don't think that you are supposed to call SmartInventory#open inside your InventoryProvider (SimpleInventory).

> I need to get the player somehow but I don't have a method to get it, what could I do?

Ask yourself: When do I need to open the SmartInventory? Is it when the player types a certain command? Or is it when some sort of event happens, like they reach experience level 100 (for example).

Depending on your answer, the solution is going to be either CommandExecutor or Listeners.

```java
// CommandExecutor
public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
	...
	if(command.getName().equals("smartinv")) {
		INVENTORY.open((Player)sender);
	}
}

// Listener
@EventHandler
public void onXpLevelChange(PlayerLevelChangeEvent event) {
	if(event.getNewLevel() == 100) {
		INVENTORY.open(event.getPlayer());
	}
}
```
