### ISSUE TITLE
SlotIterator override setting not working

### ISSUE THREAD

**Issue by crysis992** [MinusKube/SmartInvs#8]
Thanks for implementing my feature requests so incredible fast, thats awesome!

The allowOverride method from last commit does not work properly. It does still override already existing (the fillBorder items) items inside the inventory.

`
	private static final ItemStack fill = new ItemBuilder(Material.STAINED_GLASS_PANE).durability(15).name(" ").build();

	@Override
	public void init(Player player, InventoryContents contents) {

		contents.fillBorders(ClickableItem.empty(fill));

		Pagination pagination = contents.pagination();
		ArrayList<ClickableItem> items = new ArrayList<ClickableItem>();

		for (int i = 0; i < 20; i++) {
			ItemStack item = new ItemBuilder(Material.PAPER).name("§fDebug" + i).build();

			items.add(ClickableItem.of(item, e -> {
				UtilPlayer.playSound(player, Sound.BLOCK_LEVER_CLICK);
				player.sendMessage("Just a debug code");
			}));
		}
		
		contents.set(4, 6, ClickableItem.of(new ItemBuilder(Material.MAP).name("Next page").build(), e -> {
			contents.inventory().open(player, pagination.next().getPage());
		}));
		contents.set(4, 2, ClickableItem.of(new ItemBuilder(Material.MAP).name("Previous page").build(), e -> {
			contents.inventory().open(player, pagination.previous().getPage());
		}));
		

		ClickableItem[] c = new ClickableItem[items.size()];
		c = items.toArray(c);

		pagination.setItems(c);
		pagination.setItemsPerPage(18);

		SlotIterator slotIterator = contents.newIterator(Type.HORIZONTAL, 1, 0);
		slotIterator = slotIterator.allowOverride(false);
		pagination.addToIterator(slotIterator);
	}
`

Result:
![test](https://user-images.githubusercontent.com/5308174/41131080-02896da2-6aba-11e8-9acf-d7af9c41e36d.png)

Is there anything I'm doing wrong? The border shouldn't be filled with the override setting but it doesn't seem to work.

**Comment by MinusKube** [comment]
Sorry, I currently can't test the changes I made since the last version ^^' I'll be able to test in 1 week, meanwhile, you can still use the `SlotIterator#blacklist(row, column)` method and blacklist all the glass panes
