### ISSUE TITLE
I can't serialize a section

### ISSUE THREAD

**Issue by Nahuel1421** [MinusKube/SmartInvs#97]
My Code:
`for(String itemkey : plugin.getConfig().getConfigurationSection("Menu.Items").getKeys(false)) {
			contents.set(plugin.getConfig().getConfigurationSection("Menu.Items."+itemkey).getInt("X"),
			plugin.getConfig().getConfigurationSection("Menu.Items."+itemkey).getInt("X"),
			ClickableItem.empty(new ItemStack(Material.IRON_SWORD)));	
}`
Error:
`org.bukkit.command.CommandException: Unhandled exception executing command 'menu' in plugin Menu v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
        at me.Menu.Main.InventoryProvider.init(InventoryProvider.java:19) ~[?:?]
        at fr.minuskube.inv.SmartInventory.open(SmartInventory.java:52) ~[?:?]
        at fr.minuskube.inv.SmartInventory.open(SmartInventory.java:35) ~[?:?]
        at me.Menu.Main.Command.onCommand(Command.java:20) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        ... 15 more`
It happens that I try to obtain a section of my list to be able to obtain items id, positions X and Y etc. My list is fine, but when executing the command / menu open (which opens the menu) I receive an error in the nullpointerexception console which points to the for.

**Comment by portlek** [comment]
please write the code with 3 `

**Comment by Sytm** [comment]
Could you please provide your entire `me.Menu.Main.InventoryProvider` file please so I can see what happens around line 19

**Comment by Nahuel1421** [comment]
> ¿Podría proporcionar su `me.Menu.Main.InventoryProvider`archivo completo por favor para que pueda ver lo que sucede alrededor de la línea 19. Además, parece que está leyendo la coordenada X dos veces y la usa como x e y.
> 
> ```java
> for ( String itemkey : plugin . getConfig () . getConfigurationSection ( " Menu.Items " ) . getKeys ( false )) { 
> 	contenido . set (plugin . getConfig () . getConfigurationSection ( " Menu.Items. "  + itemkey) . getInt ( " X " ), // <- AQUÍ 
> 		plugin . getConfig () . getConfigurationSection ( " Menu.Items " . + itemkey) . getInt ( " X " ), // <- Y AQUÍ 
> 		ClickableItem . vacío ( nuevo  ItemStack ( Material . IRON_SWORD ))); 
> }
> ```

**Comment by Nahuel1421** [comment]
> ¿Podría proporcionar su `me.Menu.Main.InventoryProvider`archivo completo por favor para que pueda ver lo que sucede alrededor de la línea 19. Además, parece que está leyendo la coordenada X dos veces y la usa como x e y.
> 
> ```java
> for ( String itemkey : plugin . getConfig () . getConfigurationSection ( " Menu.Items " ) . getKeys ( false )) { 
> 	contenido . set (plugin . getConfig () . getConfigurationSection ( " Menu.Items. "  + itemkey) . getInt ( " X " ), // <- AQUÍ 
> 		plugin . getConfig () . getConfigurationSection ( " Menu.Items " . + itemkey) . getInt ( " X " ), // <- Y AQUÍ 
> 		ClickableItem . vacío ( nuevo  ItemStack ( Material . IRON_SWORD ))); 
> }
> ```

**Comment by Nahuel1421** [comment]
> ¿Podría proporcionar su `me.Menu.Main.InventoryProvider`archivo completo por favor para que pueda ver lo que sucede alrededor de la línea 19. Además, parece que está leyendo la coordenada X dos veces y la usa como x e y.
> 
> ```java
> for ( String itemkey : plugin . getConfig () . getConfigurationSection ( " Menu.Items " ) . getKeys ( false )) { 
> 	contenido . set (plugin . getConfig () . getConfigurationSection ( " Menu.Items. "  + itemkey) . getInt ( " X " ), // <- AQUÍ 
> 		plugin . getConfig () . getConfigurationSection ( " Menu.Items " . + itemkey) . getInt ( " X " ), // <- Y AQUÍ 
> 		ClickableItem . vacío ( nuevo  ItemStack ( Material . IRON_SWORD ))); 
> }
> ```
Sytm, you're right, I've already corrected that but it's still the same, now I'll send the whole class

**Comment by Nahuel1421** [comment]
package me.Menu.Main;

import java.util.Set;

import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import fr.minuskube.inv.ClickableItem;
import fr.minuskube.inv.content.InventoryContents;
	
public class InventoryProviders implements fr.minuskube.inv.content.InventoryProvider {

	private final Main plugin;
	public InventoryProviders(Main plugin) {
		this.plugin = plugin;
	}
	static String itemkey;
	public static InventoryContents contents;
	@SuppressWarnings("static-access")
	@Override
	public void init(Player player, InventoryContents contents) {
		this.contents = contents;
		for(String itemkey : plugin.getConfig().getConfigurationSection("Menu.Items").getKeys(false)) {
			contents.set(1,
			1,
			ClickableItem.empty(new ItemStack(Material.valueOf(plugin.getConfig().getString("Menu.Items."+itemkey+".ID")))));	
		}
	}

	@Override
	public void update(Player player, InventoryContents contents) {
        
	}
}

>```

**Comment by Sytm** [comment]
Could it be that you changed the file meanwhile? Because line 19 (Where the NullPointerException occurred) is just
```java
public static InventoryContents contents;
```
Maybe try again and if the error occurred again, send the new stack trace please

**Comment by Nahuel1421** [comment]
> Could it be that you changed the file meanwhile? Because line 19 (Where the NullPointerException occurred) is just
> 
> ```java
> public static InventoryContents contents;
> ```
> 
> Maybe try again and if the error occurred again, send the new stack trace please

Yes im sorry.
```java
package me.Menu.Main;


import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import fr.minuskube.inv.ClickableItem;
import fr.minuskube.inv.content.InventoryContents;
	
public class InventoryProviders implements fr.minuskube.inv.content.InventoryProvider {

	private final Main plugin;
	public InventoryProviders(Main plugin) {
		this.plugin = plugin;
	}
	@Override
	public void init(Player player, InventoryContents contents) {
		for(String itemkey : plugin.getConfig().getConfigurationSection("Menu.Items").getKeys(false)) {
			contents.set(1,
			1,
			ClickableItem.empty(new ItemStack(Material.valueOf(plugin.getConfig().getString("Menu.Items."+itemkey+".ID")))));	
		}
	}

	@Override
	public void update(Player player, InventoryContents contents) {
        
	}
}
```

**Comment by Nahuel1421** [comment]
And if necessary
`Menu:
  Items:
    '1':
      ID: IRON_SWORD
      X: 1
      Y: 1
`

**Comment by Sytm** [comment]
The two problems I could think of, is that `plugin` is null or the `plugin.getConfig()` is null.

But the `.getConfigurationSection("Menu.Items").getKeys(false)` looks alright to me, as it matches your actual config. What you could try is to separate each possible cause into a new line like this:
```java
for(String itemkey : plugin
	.getConfig()
	.getConfigurationSection("Menu.Items")
	.getKeys(false)) {
	contents.set(1,
	1,
	ClickableItem.empty(new ItemStack(Material.valueOf(plugin.getConfig().getString("Menu.Items."+itemkey+".ID")))));	
}

```

**Comment by Nahuel1421** [comment]
> The two problems I could think of, is that `plugin` is null or the `plugin.getConfig()` is null.
> 
> But the `.getConfigurationSection("Menu.Items").getKeys(false)` looks alright to me, as it matches your actual config. What you could try is to separate each possible cause into a new line like this:
> 
> ```java
> for(String itemkey : plugin
> 	.getConfig()
> 	.getConfigurationSection("Menu.Items")
> 	.getKeys(false)) {
> 	contents.set(1,
> 	1,
> 	ClickableItem.empty(new ItemStack(Material.valueOf(plugin.getConfig().getString("Menu.Items."+itemkey+".ID")))));	
> }
> ```

It seems that plugin.getConfig () is null, this happens only in the InventoryProviders class since I tested using a command that contains a config string using plugin.getConfig (). GetSttring (string);
if it has worked, it is only in inventoryproviders that plugin.getConfig () is null

**Comment by Nahuel1421** [comment]
It even occurred to me to remove the for and leave plugin.getConfig (). GetString (string) in the Material.Valueof ()
and it has not worked either

**Comment by Sytm** [comment]
> plugin.getConfig ()
Looks like you are not passing the plugins instance in the constructor
```java
public InventoryProviders(Main plugin) {
	this.plugin = plugin; // Already null here perhaps?
}
```

**Comment by Nahuel1421** [comment]
> > plugin.getConfig ()  is null
> 
> Looks like you are not passing the plugins instance in the constructor
> 
> ```java
> public InventoryProviders(Main plugin) {
> 	this.plugin = plugin; // Already null here perhaps?
> }
> ```

If I'm doing it

**Comment by Nahuel1421** [comment]
Ok, I solved it, I just put the variable out of the Init method and it worked
